version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: perpus-tsania72
    ports:
      - "8000:80"

    environment:
      - DB_HOST=db
      - DB_DATABASE=perpusku_gc
      - DB_USERNAME=tsania72
      - DB_PASSWORD=tsaniajuara1

    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: perpus-db
    environment:
      MYSQL_ROOT_PASSWORD: tsaniajuara1
      MYSQL_DATABASE: perpusku_gc
      MYSQL_USER: tsania72
      MYSQL_PASSWORD: tsaniajuara1

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


